export const styles = {
    input: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    body: "z-50 p-4 overflow-auto fixed top-0 left-0 w-full h-screen bg-black bg-opacity-75 grid place-items-center",
    form: "overflow-auto space-y-1",
    label: "block mb-2 text-sm font-medium text-gray-900 dark:text-white",
    h5: "text-xl font-medium text-gray-900 dark:text-white",
    dual: "grid grid-cols-2 gap-4 justify-center",
    input_Dual:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    button: 'mt-3 w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800',
    select: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
    div_ind: "grid grid-rows-divDesModal m-0",
    error: "text-red-500 text-sm font-semibold",
    exito: "text-sm font-semibold text-lime-400",
    div_g: "grid grid-rows-divDesImg",
    div_p: "grid grid-rows-divForm m-0",
    p: "font-medium text-gray-900 dark:text-white border-b-[3px] p-2",
    header: "mt-5 mr-5 ml-5 mb-0 w-full max-w-sm p-4 sm:p-6 md:p-8 dark:text-white",
    logo: 'font-bungee text-5xl',
    container: "overflow-auto h-auto max-h-full w-96 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white bg-opacity-90  items-center  rounded-lg border border-black p-4 pt-0 dark:bg-gray-800 dark:border-gray-700 dark:placeholder-gray-400 dark:text-white",
    plusLess: 'mx-1 w-3.5 grid place-items-center bg-blue-700 hover:bg-blue-800 focus:ring-3 focus:outline-none focus:ring-blue-300 font-medium rounded-full dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800',
    eventNotFount: "mt-2 text-xl font-bold tracking-tight bg-gradient-to-r text-transparent bg-clip-text from-blue-400 to-green-500 text-gray-900",

}